import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export enum TimelineEvent {
  LEAD_CREATED = "LEAD_CREATED",
  LEAD_NAME_CHANGED = "LEAD_NAME_CHANGED",
  LEAD_PHONE_CHANGED = "LEAD_PHONE_CHANGED",
  LEAD_EMAIL_CHANGED = "LEAD_EMAIL_CHANGED",
  LEAD_PURPOSE_CHANGED = "LEAD_PURPOSE_CHANGED",
  LEAD_OWNER_CHANGED = "LEAD_OWNER_CHANGED",
  LEAD_STATUS_CHANGED = "LEAD_STATUS_CHANGED",

  LEAD_NOTE_ADDED = "LEAD_NOTE_ADDED",
  LEAD_NOTE_DELETED = "LEAD_NOTE_DELETED",
  LEAD_NOTE_UPDATED = "LEAD_NOTE_UPDATED",

  LEAD_FOLLOWUP_ADDED = "LEAD_FOLLOWUP_ADDED",
  LEAD_FOLLOWUP_DELETED = "LEAD_FOLLOWUP_DELETED",
  LEAD_FOLLOWUP_UPDATED = "LEAD_FOLLOWUP_UPDATED",
  LEAD_FOLLOWUP_DATE_EXTENDED = "LEAD_FOLLOWUP_DATE_EXTENDED",
  LEAD_FOLLOWUP_COMPLETED = "LEAD_FOLLOWUP_COMPLETED",

  LEAD_FOLLOWUP_COMMENT_ADDED = "LEAD_FOLLOWUP_COMMENT_ADDED",
  LEAD_FOLLOWUP_COMMENT_DELETED = "LEAD_FOLLOWUP_COMMENT_DELETED",
  LEAD_FOLLOWUP_COMMENT_UPDATED = "LEAD_FOLLOWUP_COMMENT_UPDATED",
}

export type TimelineEventType = `${TimelineEvent}`;