import { ReportDefinition, ReportType } from '@/types/reports';

export const REPORT_DEFINITIONS: Record<ReportType, ReportDefinition> = {
  'study-lead': {
    type: 'study-lead',
    title: 'Study Lead Reports',
    description: 'Track lead sources, conversions, and performance metrics for better sales insights.',
    route: '/reports/study-lead',
    defaultSortBy: 'created_at',
    defaultSortOrder: 'desc',
    filters: [
      { key: 'branch', label: 'Branch' },
      { key: 'lead_status', label: 'Status' },
      { key: 'lead_counsellor', label: 'Lead Counsellor' },
      { key: 'preferred_country', label: 'Preferred Country' },
      { key: 'lead_source', label: 'Lead Source' },
      { key: 'timeline', label: 'Timeline' },
    ],
    columns: [
      { key: 'serial_no', label: 'Serial No.', mandatory: true, defaultVisible: true },
      { key: 'given_name', label: 'Given Name', defaultVisible: true },
      { key: 'surname', label: 'Surname', defaultVisible: true },
      { key: 'email', label: 'Email', defaultVisible: true },
      { key: 'phone', label: 'Phone', defaultVisible: false },
      { key: 'visa_type', label: 'Visa Type', defaultVisible: true },
      { key: 'lead_status', label: 'Lead Status', defaultVisible: true },
      { key: 'branch', label: 'Branch', defaultVisible: true },
      { key: 'lead_counsellor', label: 'Lead Counsellor', defaultVisible: true },
      { key: 'preferred_country', label: 'Preferred Country', defaultVisible: true },
      { key: 'lead_source', label: 'Lead Source', defaultVisible: false },
      { key: 'timeline', label: 'Timeline', defaultVisible: false },
    ],
  },
  counselling: {
    type: 'counselling',
    title: 'Counselling Reports',
    description: 'Track conversions and analyze performance metrics to gain better insights.',
    route: '/reports/counselling',
    defaultSortBy: 'created_at',
    defaultSortOrder: 'desc',
    filters: [
      { key: 'branch', label: 'Branch' },
      { key: 'counselling_status', label: 'Counselling Status' },
      { key: 'counsellor', label: 'Counsellor' },
      { key: 'visa_type', label: 'Visa Type' },
      { key: 'lead_source', label: 'Lead Source' },
      { key: 'timeline', label: 'Timeline' },
    ],
    columns: [
      { key: 'serial_no', label: 'Serial No.', mandatory: true, defaultVisible: true },
      { key: 'given_name', label: 'Given Name', defaultVisible: true },
      { key: 'surname', label: 'Surname', defaultVisible: true },
      { key: 'email', label: 'Email', defaultVisible: true },
      { key: 'phone', label: 'Phone', defaultVisible: true },
      { key: 'visa_type', label: 'Visa Type', defaultVisible: true },
      { key: 'branch', label: 'Branch', defaultVisible: true },
      { key: 'counsellor', label: 'Counsellor', defaultVisible: true },
      { key: 'counselling_status', label: 'Counselling Status', defaultVisible: true },
      { key: 'lead_source', label: 'Lead Source', defaultVisible: false },
      { key: 'timeline', label: 'Timeline', defaultVisible: false },
    ],
  },
  admission: {
    type: 'admission',
    title: 'Admission Reports',
    description: 'Streamline admissions from review to final enrollment.',
    route: '/reports/admission',
    defaultSortBy: 'created_at',
    defaultSortOrder: 'desc',
    filters: [
      { key: 'branch', label: 'Branch' },
      { key: 'admission_status', label: 'Admission Status' },
      { key: 'admission_manager', label: 'Admission Manager' },
      { key: 'visa_type', label: 'Visa Type' },
      { key: 'lead_source', label: 'Lead Source' },
      { key: 'timeline', label: 'Timeline' },
    ],
    columns: [
      { key: 'serial_no', label: 'Serial No.', mandatory: true, defaultVisible: true },
      { key: 'given_name', label: 'Given Name', defaultVisible: true },
      { key: 'surname', label: 'Surname', defaultVisible: true },
      { key: 'email', label: 'Email', defaultVisible: true },
      { key: 'phone', label: 'Phone', defaultVisible: true },
      { key: 'visa_type', label: 'Visa Type', defaultVisible: true },
      { key: 'branch', label: 'Branch', defaultVisible: true },
      { key: 'admission_status', label: 'Admission Status', defaultVisible: true },
      { key: 'admission_manager', label: 'Admission Manager', defaultVisible: true },
      { key: 'lead_source', label: 'Lead Source', defaultVisible: false },
      { key: 'timeline', label: 'Timeline', defaultVisible: false },
    ],
  },
  application: {
    type: 'application',
    title: 'Application Reports',
    description: 'Get real-time data on enrollment, admission funnels, and student demographics.',
    route: '/reports/application',
    defaultSortBy: 'created_at',
    defaultSortOrder: 'desc',
    filters: [
      { key: 'branch', label: 'Branch' },
      { key: 'application_status', label: 'Application Status' },
      { key: 'admission_manager', label: 'Admission Manager' },
      { key: 'country', label: 'Country' },
      { key: 'visa_type', label: 'Visa Type' },
      { key: 'timeline', label: 'Timeline' },
    ],
    columns: [
      { key: 'serial_no', label: 'Serial No.', mandatory: true, defaultVisible: true },
      { key: 'given_name', label: 'Given Name', defaultVisible: true },
      { key: 'surname', label: 'Surname', defaultVisible: true },
      { key: 'email', label: 'Email', defaultVisible: true },
      { key: 'phone', label: 'Phone', defaultVisible: true },
      { key: 'country', label: 'Country', defaultVisible: true },
      { key: 'application_status', label: 'Application Status', defaultVisible: true },
      { key: 'branch', label: 'Branch', defaultVisible: true },
      { key: 'admission_manager', label: 'Admission Manager', defaultVisible: true },
      { key: 'visa_type', label: 'Visa Type', defaultVisible: true },
      { key: 'timeline', label: 'Timeline', defaultVisible: false },
    ],
  },
  visa: {
    type: 'visa',
    title: 'Visa Reports',
    description: 'Streamline visa application process and monitor approvals and denials.',
    route: '/reports/visa',
    defaultSortBy: 'created_at',
    defaultSortOrder: 'desc',
    filters: [
      { key: 'branch', label: 'Branch' },
      { key: 'visa_status', label: 'Visa Status' },
      { key: 'visa_manager', label: 'Visa Manager' },
      { key: 'country', label: 'Country' },
      { key: 'applied_via', label: 'Applied Via' },
      { key: 'intake', label: 'Intake' },
      { key: 'visa_type', label: 'Visa Type' },
      { key: 'timeline', label: 'Timeline' },
    ],
    columns: [
      { key: 'serial_no', label: 'Serial No.', mandatory: true, defaultVisible: true },
      { key: 'given_name', label: 'Given Name', defaultVisible: true },
      { key: 'surname', label: 'Surname', defaultVisible: true },
      { key: 'email', label: 'Email', defaultVisible: true },
      { key: 'phone', label: 'Phone', defaultVisible: true },
      { key: 'country', label: 'Country', defaultVisible: true },
      { key: 'visa_status', label: 'Visa Status', defaultVisible: true },
      { key: 'branch', label: 'Branch', defaultVisible: true },
      { key: 'visa_manager', label: 'Visa Manager', defaultVisible: true },
      { key: 'applied_via', label: 'Applied Via', defaultVisible: false },
      { key: 'intake', label: 'Intake', defaultVisible: false },
      { key: 'visa_type', label: 'Visa Type', defaultVisible: false },
      { key: 'timeline', label: 'Timeline', defaultVisible: false },
    ],
  },
  payment: {
    type: 'payment',
    title: 'Payment Reports',
    description: 'Track payment flows and transaction histories to uncover revenue trends.',
    route: '/reports/payment',
    defaultSortBy: 'created_at',
    defaultSortOrder: 'desc',
    filters: [
      { key: 'branch', label: 'Branch' },
      { key: 'payment_status', label: 'Payment Status' },
      { key: 'payment_type', label: 'Payment Type' },
      { key: 'lead_type', label: 'Lead Type' },
      { key: 'payment_mode', label: 'Payment Mode' },
      { key: 'payment_stage', label: 'Payment Stage' },
      { key: 'lead_source', label: 'Lead Source' },
      { key: 'timeline', label: 'Payment Date' },
    ],
    columns: [
      { key: 'serial_no', label: 'Serial No.', mandatory: true, defaultVisible: true },
      { key: 'given_name', label: 'Given Name', defaultVisible: true },
      { key: 'surname', label: 'Surname', defaultVisible: true },
      { key: 'email', label: 'Email', defaultVisible: true },
      { key: 'phone', label: 'Phone', defaultVisible: true },
      { key: 'lead_type', label: 'Lead Type', defaultVisible: true },
      { key: 'payment_status', label: 'Payment Status', defaultVisible: true },
      { key: 'currency', label: 'Currency', defaultVisible: true },
      { key: 'payment_amount', label: 'Payment Amount', defaultVisible: true },
      { key: 'payment_type', label: 'Payment Type', defaultVisible: true },
      { key: 'payment_mode', label: 'Payment Mode', defaultVisible: false },
      { key: 'payment_stage', label: 'Payment Stage', defaultVisible: false },
      { key: 'branch', label: 'Branch', defaultVisible: false },
      { key: 'timeline', label: 'Payment Date', defaultVisible: false },
    ],
  },
  'follow-up': {
    type: 'follow-up',
    title: 'Follow Up Reports',
    description: 'Track follow up activity and team performance metrics.',
    route: '/reports/follow-up',
    defaultSortBy: 'created_at',
    defaultSortOrder: 'desc',
    filters: [
      { key: 'branch', label: 'Branch' },
      { key: 'status', label: 'Status' },
      { key: 'lead_type', label: 'Lead Type' },
      { key: 'timeline', label: 'Timeline' },
      { key: 'entity', label: 'Entity' },
    ],
    columns: [
      { key: 'serial_no', label: 'Serial No.', mandatory: true, defaultVisible: true },
      { key: 'given_name', label: 'Given Name', defaultVisible: true },
      { key: 'surname', label: 'Surname', defaultVisible: true },
      { key: 'phone', label: 'Phone', defaultVisible: true },
      { key: 'branch', label: 'Branch', defaultVisible: true },
      { key: 'follow_up', label: 'Follow Up', defaultVisible: true },
      { key: 'entity', label: 'Entity', defaultVisible: true },
      { key: 'status', label: 'Status', defaultVisible: true },
      { key: 'lead_type', label: 'Lead Type', defaultVisible: true },
      { key: 'timeline', label: 'Timeline', defaultVisible: false },
    ],
  },
};

export const REPORT_CARDS = Object.values(REPORT_DEFINITIONS);
